### ISSUE TITLE
Roadmap for V2 of the ML Model Extension

### ISSUE THREAD

**Issue by rbavery** [crim-ca/dlm-extension#7]
Below are acceptance criteria for #2 the new version of the ML Model Extension. After all these items are done I think #2 is ready to merge and we can publish a new version 2 release to https://github.com/stac-extensions/ml-model/issues . I'm working on most of these, let me know if you think other acceptance criteria should be included cc @fmigneault 

- [x] Incorporate feedback from @fmariv and others at @earthpulse 
    - I had a meeting with @fmariv, they're keen to review the extension, provide feedback and see if we can align it more with general ML use cases. They're working on supporting the STAC extension ecosystem for ML as a part of the [EOTDL](https://www.eotdl.com/) initiative
    - https://hackmd.io/DBRF1sQCS1WmSqygJNKQJQ?view
    - feel free to comment first and then submit a PR against https://github.com/rbavery/dlm-extension/tree/validate
- [x] address #5 
    - this will involve segregating flat fields from objects that are not meant to be searched on and are instead used for inference model loading, model input and output processing, and documenting in detail the accelerator and runtime details needed to run the model
- [ ] ~~#4 by creating output objects for common detection tasks. At a minimum, start with single label classification, semantic segmentation, object detection. This will help resolve common ambiguities when interpreting model outputs, like the bbox coordinate ordering for object detection.~~ EDIT this can be left for after the v2 release
- [ ] resolve #3, deciding how to refer to model extension metadata. within it's own STAC item/collection json or are these fields composed with common metadata in STAC json representing a spatiotemporal asset?
- [x] https://github.com/crim-ca/dlm-extension/pull/2#discussion_r1446651049 create an example and schema for the final spec
- [x] reorganize and update the stac_model extension validation and serialization package according to the final spec: https://github.com/crim-ca/dlm-extension/pull/2#issuecomment-1882002335
- [x] https://github.com/rbavery/dlm-extension/pull/2
- [ ] consider inputs from user feedback (https://github.com/stac-extensions/ml-model/issues/13)
- [ ] consider community examples applying DLM (https://github.com/sentinel-hub/stac-ml-example) 
- [x] #8 
- [x] #9 
- [x] #12
- [x] #13
- [x] integrate JSON schema representing new properties/fields (mix of https://github.com/crim-ca/dlm-extension/tree/main/json-schema and https://github.com/rbavery/dlm-extension/pull/1)
- [x] #14
- [ ] https://github.com/stac-extensions/classification/issues/48
- [ ] https://github.com/stac-extensions/example-links/issues/4
- [ ] https://github.com/stac-extensions/processing/issues/31
- [ ] https://github.com/stac-extensions/processing/pull/33
- [ ] consideration of `end_datetime: null` not supported by STAC Core spec 
  (https://github.com/radiantearth/stac-spec/issues/1268)

**Comment by devisperessutti** [comment]
Added some comments to the HackMD summary file.

Happy to take on some of the tasks above to push this forward.

**Comment by rbavery** [comment]
Hi @devisperessutti thanks a bunch. I talked with Francis and I think the main things left to do are to update the example with the current spec (which I can do) and to make a schema json that follows the README description of the schema.

We now have an [example.json](https://github.com/crim-ca/dlm-extension/pull/2#issuecomment-1970058814) that combines required pystac common metadata with required ML Model Extension metadata. do you want to take a stab at writing the schema json and PR that against stac-extensions/example-links#2  ? I'm happy to review and assist.

I think improving the spec so that output tasks have their own object structure can be a to do for post Version 2 so that we can start contributing smaller PRs after this large refactor.

**Comment by devisperessutti** [comment]
> We now have an [example.json](https://github.com/crim-ca/dlm-extension/pull/2#issuecomment-1970058814) that combines required pystac common metadata with required ML Model Extension metadata. do you want to take a stab at writing the schema json and PR that against stac-extensions/example-links#2 ? I'm happy to review and assist.

Sounds good, I'll try to tackle this early next week.

**Comment by fmigneault** [comment]
Related by not directly impacting the roadmap: https://github.com/stac-extensions/ml-aoi/pull/8

**Comment by fmigneault** [comment]
@rbavery 
With https://github.com/rbavery/dlm-extension/pull/2, I now got functioning JSON-schema validation against a few JSON examples using different combinations of STAC extensions. I applied a few modifications to the `pydantic`/`pystac` definitions to better align with the schema. There might be some discrepancies here and there, such as `minItems` not perfectly validated the same way, but the `eurosat_resnet` example loaded as `pystac.Item` works against the JSON schema as well. I only got a minor validation of `bands` property that I need to fix to wrap things up (see `"FIXME_$ref": "#/$defs/AnyBandsRef"` in the schema).

I would like to get your review of https://github.com/rbavery/dlm-extension/pull/2 so that we can integrate it in https://github.com/crim-ca/dlm-extension/pull/2, and realign all branches together.

**Comment by fmigneault** [comment]
@devisperessutti 
I invite you to push updates from your samples in https://github.com/sentinel-hub/stac-ml-example using MLM fields updates from https://github.com/rbavery/dlm-extension/pull/2. 
Specifically, you can add your samples in the `examples/` directory, and then add them to this test (https://github.com/rbavery/dlm-extension/blob/4eb30dab98617dfee4cc6b1e5dbc1d50d4770779/tests/test_schema.py#L8-L18) to validate them against the definitions. 
If the test passes, that will allow us to ensure your use cases remain compatible with the extension schema.
Additional feedback/questions welcome.

**Comment by fmigneault** [comment]
Moved to https://github.com/crim-ca/mlm-extension/issues/4
